### ISSUE TITLE
Some request go to "The request timed out."

### ISSUE THREAD

**Issue by andr3a88** [Constantine-Fry/Foursquare-API-v2#82]
In my application I have after some days that the user logged in the message "The request timed out." for the Foursquare request. This problema cause the block of UI for the timeoutInterval (30sec).

I can not figure out if the problem can be the session token expired. Is possible to check if the token is still valid? ([Foursquare2 isAuthorized] return always YES). I need to refresh the token every time the app is launched? Other explanations?

**Comment by Constantine-Fry** [comment]
Hi, here is quote from foursquare [documentation](https://developer.foursquare.com/overview/auth)
```
 Access tokens do not expire, but they may be revoked by the user.
```

The  request timed out usually happens when user have veery slow internet connection. This error is thrown when request were trying to perform longer then timeoutInterval value. What timeout interval do you use for requests?

**Comment by Constantine-Fry** [comment]
if you timeoutInterval is 30 then of course you will have time out error very often.

**Comment by andr3a88** [comment]
I set timeoutInterval to 15, i have some troubles when 3g connection is very slow, (sometimes fails to ping) the UI freezes and the user cannot navigate the App

**Comment by Constantine-Fry** [comment]
So that's a problem. Making timeoutInterval short is not a solution for freezing UI.
Library itself should not freeze UI. How do you use API calls? Can you show me you code snippets?

**Comment by andr3a88** [comment]
Here https://gist.github.com/andr3a88/49e88ab00262bcaf6f43 my code

**Comment by Constantine-Fry** [comment]
In your snippet i see no problems. How do you block/freez the UI in your app?

**Comment by andr3a88** [comment]
I still don't understand, I have to investigate
