### ISSUE TITLE
Strange behavior in nativeAuthorization

### ISSUE THREAD

**Issue by dkorkin** [Constantine-Fry/Foursquare-API-v2#83]
After the execution of 
[sharedApplication openURL:authURL];
in FSOAuthNoAppStore and returns Foursquare app opened and nothing happens, but I suppose redirect to your test app.
In the case when Foursquare application has already been opened on device it's woks fine.

**Comment by andr3a88** [comment]
i have the same problem!

**Comment by Constantine-Fry** [comment]
Hi, did you you follow the instructions in readme file? Make sure you have added URL scheme in info.plist.

![screen shot 2015-03-29 at 12 32 59](https://cloud.githubusercontent.com/assets/239692/6885070/c303f78e-d60f-11e4-9adf-f328ea3047d3.png)

**Comment by andr3a88** [comment]
The problem occurs only when Foursquare app is not already opened. I think it's a "Foursquare" side problem

**Comment by dkorkin** [comment]
Maybe method
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
in "Foursquare" app doesn't handle UIApplicationLaunchOptionsURLKey correctly?

**Comment by Constantine-Fry** [comment]
I've just tested the demo application from repository and it works there. Have you found what's the problem?

**Comment by dkorkin** [comment]
Did you test the case when your Foursquare not in bg mode (not in iphone memory, your used did not auth in app)?

**Comment by Constantine-Fry** [comment]
I run Foursquare2 demo app, tap on cell with venue it redirected me to Foursquare app and bock to the demo app. How do you do it?

**Comment by dkorkin** [comment]
Full steps I log out from FS app, then I kill it, launch your example, press checking, relaunched me to FS app, (now I see alert Log in or Sign up to connect application and then try connecting again) but previous time I logged in  and nothing happened (no redirect to test app)

**Comment by Constantine-Fry** [comment]
But does it work if you do not log out from FS app?

**Comment by dkorkin** [comment]
Yes and it also worked in case when I was logged out and FS app worked in bg mode

**Comment by Constantine-Fry** [comment]
Interesting. It actually works for me. Do you login with emali/password or with Facebook account?

**Comment by dkorkin** [comment]
I using emal&password   (p.s swarm app was without auth, but I don't think that it influenced on process)

**Comment by Constantine-Fry** [comment]
It's very strange. But I suppose it's a bug in Foursquare app.

**Comment by dkorkin** [comment]
Analyzing  this issue I came to same conclusion and removed lib from pods to vendors, commented native auth for better times. Thanks for feedback!

**Comment by andr3a88** [comment]
With the last version of Foursquare App (released today) it seems that the issue is resolved.
