### ISSUE TITLE
Why did you deprecate the library? Is it still usable?

### ISSUE THREAD

**Issue by Ge0rges** [Constantine-Fry/Foursquare-API-v2#84]
Hi, I just wanted to know why you deprecated this awesome library and if it is still usable for projects using Objective-C

**Comment by Constantine-Fry** [comment]
It's still usable, but I really recommend the use https://github.com/Constantine-Fry/das-quadrat.

**Comment by Ge0rges** [comment]
Ok thank you for the swift response!
